// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDacW1Ef7ZLzRtp2hAuqECtB5wMuviPnuY',
    appId: '1:923639657340:web:b28e8f05abab2a730e2af9',
    messagingSenderId: '923639657340',
    projectId: 'agenda-dev-298ae',
    authDomain: 'agenda-dev-298ae.firebaseapp.com',
    storageBucket: 'agenda-dev-298ae.firebasestorage.app',
    measurementId: 'G-ZRB1D8FWXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa8-E_18d_E3Ls75OJu13XGz2VfV9WRes',
    appId: '1:923639657340:android:948c9c4b7476a6e40e2af9',
    messagingSenderId: '923639657340',
    projectId: 'agenda-dev-298ae',
    storageBucket: 'agenda-dev-298ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0Cbt3UaLP4_QOu4EvvdEY9TErcEFcVRM',
    appId: '1:923639657340:ios:1081feda2f71c9c40e2af9',
    messagingSenderId: '923639657340',
    projectId: 'agenda-dev-298ae',
    storageBucket: 'agenda-dev-298ae.firebasestorage.app',
    iosBundleId: 'com.example.agendaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0Cbt3UaLP4_QOu4EvvdEY9TErcEFcVRM',
    appId: '1:923639657340:ios:1081feda2f71c9c40e2af9',
    messagingSenderId: '923639657340',
    projectId: 'agenda-dev-298ae',
    storageBucket: 'agenda-dev-298ae.firebasestorage.app',
    iosBundleId: 'com.example.agendaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDacW1Ef7ZLzRtp2hAuqECtB5wMuviPnuY',
    appId: '1:923639657340:web:7969784ee0f6ac680e2af9',
    messagingSenderId: '923639657340',
    projectId: 'agenda-dev-298ae',
    authDomain: 'agenda-dev-298ae.firebaseapp.com',
    storageBucket: 'agenda-dev-298ae.firebasestorage.app',
    measurementId: 'G-EF9Z7L7T6X',
  );
}
